services:
  app:
    image: workout-app-frontend-dev
    build:
      context: ./frontend 
      dockerfile: dev.Dockerfile 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000/graphql
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app 
    ports:
      - 3000:3000
    container_name: workout-front-dev

  backend:
    image: workout-app-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    environment:
      FLASK_ENV: development
      DB_URL: postgresql://postgres:password@postgres-db:5432/workout-db
    # healthcheck
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes: 
      - ./backend/src:/usr/src
    container_name: workout-app-backend-dev
    ports:
      - 5000:5000

  postgres-db:
      image: postgres:14.2-alpine
      ports:
        - 5432:5432
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: workout-db
      container_name: workout-app-postgres-dev
      volumes:
        - ./postgres_dev_data:/var/lib/postgresql/data

  pgadmin:
    container_name: workout-pgadmin-dev
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      GUNICORN_ACCESS_LOGFILE: /dev/null
    ports:
      - "8098:80"